### ISSUE TITLE
Can not start CMPDL on arch linux

### ISSUE THREAD

**Issue by jambonmcyeah** [Vazkii/CMPDL#20]
Java Version: 1.7.0_131
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: vazkii/cmpdl/CMPDL : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by Nincodedo** [comment]
I think this project requires Java 8+

**Comment by HellishINC** [comment]
Works on Arch with JDK + JRE 8.

Have not tested OpenJDK/JRE.
