### ISSUE TITLE
Help! There are illegal characters in my path!

### ISSUE THREAD

**Issue by Turmfalke2** [Vazkii/CMPDL#24]
hi,
Seems like cmpdl has an issue with urls/paths that include an ^.

~ Starting magical modpack download sequence ~
java.net.URISyntaxException: Illegal character in path at index 60: https://addons.cursecdn.com/files/2363/358/Material%20Energy^Natural%20Capital-0.11.04.zip
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at vazkii.cmpdl.CMPDL.getLocationHeader(CMPDL.java:346)
        at vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:86)
        at vazkii.cmpdl.OperatorThread.run(OperatorThread.java:19)

I am unsure on why curse isn't encoding the ^ as %5E, but maybe cmpdl could fix the urls instead of just failing?

**Comment by Franckyi** [comment]
Can you try using [my version](https://github.com/Franckyi/CMPDL) of CMPDL ?

**Comment by frenchiveruti** [comment]
@Franckyi Why's yours not related to Vazkii's CMPDL, you should fork a repository not create a new one from scratch.

**Comment by Franckyi** [comment]
Because I rewritten everything. He said there was no need to fork it.

_Sent from my Samsung SM-A310F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
