### ISSUE TITLE
java.lang.IllegalArgumentException: This modpack has no manifest

### ISSUE THREAD

**Issue by snigel** [Vazkii/CMPDL#33]
Trying to install https://minecraft.curseforge.com/projects/all-the-mods-3/
It fails on two mods;
https://minecraft.curseforge.com/projects/draconic-evolution/
https://minecraft.curseforge.com/projects/minecolonies/

Installing them manually gives:
```
Done unzipping
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: This modpack has no manifest
	at vazkii.cmpdl.CMPDL.main(CMPDL.java:49)
Caused by: java.lang.IllegalArgumentException: This modpack has no manifest
	at vazkii.cmpdl.CMPDL.getManifest(CMPDL.java:196)
	at vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:100)
	at vazkii.cmpdl.CMPDL.main(CMPDL.java:47)
```

But when I look at the jar files for both mods, they have manifest files located at META-INF/MANIFEST.MF

**Comment by snigel** [comment]
After more looking in to this, I realized that it's not the java manifest cmpdl is looking at.
I also found that the server rejected me and wanted specific versions which couldn't be found at curse.
Strangely my friends on windows have managed to install via twitch and get those versions.

Anyway, not a bug/issue.
