### ISSUE TITLE
cmpdl can't download any version of Pam's Harvestcraft

### ISSUE THREAD

**Issue by nekoexmachina** [Vazkii/CMPDL#35]
> Downloading 221857/2523355
> Project URL is http://minecraft.curseforge.com/projects/221857
> File download URL is https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2523355/download
> Downloading Pam%27s HarvestCraft 1.12.2m.jar
> Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://media.forgecdn.net/files/2523/355/Pam%2527s+HarvestCraft+1.12.2m.jar
> 	at vazkii.cmpdl.CMPDL.main(CMPDL.java:49)
> Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://media.forgecdn.net/files/2523/355/Pam%2527s+HarvestCraft+1.12.2m.jar
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at java.net.URL.openStream(URL.java:1045)
> 	at vazkii.cmpdl.CMPDL.downloadFileFromURL(CMPDL.java:369)
> 	at vazkii.cmpdl.CMPDL.downloadFile(CMPDL.java:325)
> 	at vazkii.cmpdl.CMPDL.downloadModpackFromManifest(CMPDL.java:218)
> 	at vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:107)
> 	at vazkii.cmpdl.CMPDL.main(CMPDL.java:47)
>

**Comment by nekoexmachina** [comment]
Same happens for 1.7.10 version

**Comment by ranid007** [comment]
same problem with bibliocraft. I try to download "Divine Journey" modpack and it fail on downloading Bibliocraft 1.11.4(id2264882) with error 403. I think this problem with Curseforge. Not with this programm.

**Comment by ranid007** [comment]
Maybe its problem with Curseforge. Not sure about programm bag

**Comment by loa-in-** [comment]
Related issue: #34

**Comment by megamanisepic** [comment]
I'll try to fix this at the moment, it can't be downloaded though. It doesn't break modpack downloading anymore.
