### ISSUE TITLE
Pam's Harvestcraft can't be used even after downloading

### ISSUE THREAD

**Issue by Maykeye** [Vazkii/CMPDL#43]
Even after patching URL parsing with  https://github.com/Vazkii/CMPDL/pull/44 Pam doesn't want to play nicely

       Downloading zip file Pam's+HarvestCraft+1.12.2q.jar.zip
       Unzipping file
       Done unzipping
       Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: This modpack has no manifest
       	at vazkii.cmpdl.CMPDL.main(CMPDL.java:49)
       Caused by: java.lang.IllegalArgumentException: This modpack has no manifest
       	at vazkii.cmpdl.CMPDL.getManifest(CMPDL.java:196)
       	at vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:100)
       	at vazkii.cmpdl.CMPDL.main(CMPDL.java:47)

Error doesn't lie: there's no manifest.json in the archive. There's mcmod.info however.

**Comment by enderger** [comment]
This is for downloading modPACKS.

**Comment by enderger** [comment]
Pams is a MOD

**Comment by Maykeye** [comment]
I see. I got confused because urls have the same syntax
