### ISSUE TITLE
CMPDL Not working - Download URL format changed on site.

### ISSUE THREAD

**Issue by ProfAggressor** [Vazkii/CMPDL#57]
Curseforge has changed their URL format.  It's not a big change, but it effectively disables CMPDL.

Where CMPDL is downloading files from "[project]/files/[file-id]/download"
Curseforge now hosts downloads at "[project]/download/[file-id]"

It's a simple spell, but quite unbreakable.

**Comment by HenryLoenwind** [comment]
see #56

**Comment by ProfAggressor** [comment]
> see #56

Thanks.  Should I close the issue?

**Comment by mightybruno** [comment]
I've fixed it here: https://github.com/mightybruno/CMPDL/releases/tag/1.2-fixed
if you have any issues I can fix them as the owner of this repo seems to be inactive. Note, that you have to specify the modpack file id manually (latest won't work)

**Comment by Vazkii** [comment]
Been focusing on quark. I'll try and have this pulled later today.

**Comment by mightybruno** [comment]
@Vazkii you should use `static` less :smile:

**Comment by Vazkii** [comment]
Should be good with the latest update.

**Comment by sarahsturgeon** [comment]
It's not good with the latest update:

```
minecraft@home:/my/minecraft/dir$ java -jar cmpdl-1.2.1.jar https://www.curseforge.com/minecraft/modpacks/my-modpack my-id
~ Starting magical modpack download sequence ~
Input URL: https://www.curseforge.com/minecraft/modpacks/my-modpack
Input Version: my-id
File URL: https://www.curseforge.com/minecraft/modpacks/my-modpack/files/my-id/download
Final URL: https://www.curseforge.com/minecraft/modpacks/my-modpack/files/my-id/download

Modpack filename is download
CMPDL Temp Dir is /home/minecraft/.cmpdl_temp
Modpack temporary directory is /home/minecraft/.cmpdl_temp/download
Directory doesn't exist, making it now
Downloading zip file download.zip
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: https://www.curseforge.com/minecraft/modpacks/my-modpack/files/my-id/download
        at vazkii.cmpdl.CMPDL.main(CMPDL.java:49)
Caused by: java.io.FileNotFoundException: https://www.curseforge.com/minecraft/modpacks/my-modpack/files/my-id/download
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
        at java.base/java.net.URL.openStream(URL.java:1140)
        at vazkii.cmpdl.CMPDL.downloadFileFromURL(CMPDL.java:369)
        at vazkii.cmpdl.CMPDL.setupModpackMetadata(CMPDL.java:167)
        at vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:99)
        at vazkii.cmpdl.CMPDL.main(CMPDL.java:47)
```

Note here:
```
Caused by: java.io.FileNotFoundException: https://www.curseforge.com/minecraft/modpacks/my-modpack/files/my-id/download
```

When the URL (I believe) should be: 
```
https://www.curseforge.com/minecraft/modpacks/my-modpack/download/my-id
```
